# Generated by Django 3.1.3 on 2021-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=0, upload_to='documents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
